project:
  type: website
  output-dir: docs

website:
  title: "Lauren Baird"
  navbar: 
    style: "docked"
    collapse-below: "sm"
    border: false
    search: false
    title: false
    background: transparent
    foreground: white
    left:
      - icon: list
        menu:
           - text: LinkedIn
             href: https://www.linkedin.com/in/laurenkbaird/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

execute:
  freeze: auto

